format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$python\
$rust\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$cmd_duration\
$line_break\
$character\
"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 8

[time]
disabled = false
time_format = "%T"
format = "[$time]($style) "
